/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package medicalapp;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kamosh Mesi
 */
public class AddMedicines extends javax.swing.JFrame {
    
    Connection Conn;
    ResultSet rs;
    PreparedStatement pst;
    Statement st;
    String date = java.time.LocalDate.now().toString();

    /** Creates new form AddMedicines */
    public AddMedicines() {
        initComponents();
        Conn = connection.ConnectDb();
        showMedicines();
        
    }
    
    public ArrayList<Medicines> medicineList()
    {
        ArrayList<Medicines> medicineList = new ArrayList<>(); 
        
        String sql = "select * from tbl_drugs";
        
        try{
            st = Conn.createStatement();
            rs = st.executeQuery(sql);
            Medicines medicines;
            while(rs.next())
            {
                medicines = new Medicines(rs.getInt("Dno"),rs.getString("Dname"),rs.getString("cutOff"),rs.getInt("Qty"),rs.getString("ARange"),rs.getInt("Amount"),rs.getString("Date"));
                medicineList.add(medicines);
            }
            
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        
        return medicineList;
    }
    
    public void showMedicines()
    {
        ArrayList<Medicines> list = medicineList();
        DefaultTableModel model = (DefaultTableModel)tbl_medi.getModel();
        Object[] row = new Object[7];
        for(int i= 0;i<list.size();i++)
        {
            row[0] = list.get(i).getDno();
            row[1] = list.get(i).getDname();
            row[2] = list.get(i).getCutOff();
            row[3] = list.get(i).getQty();
            row[4] = list.get(i).getARange();
            row[5] = list.get(i).getAmount();
            row[6] = list.get(i).getDate();
            model.addRow(row);
        }
        
        
    }
    
    public void clearData()
    {
        txt_DNo.setText("");txt_Dname.setText("");txt_ageRange.setText("");txt_amount.setText("");txt_cutOff.setText("");txt_date.setText("");txt_qty.setText("");
    }
    
    public void generateDNO()
    {
        String sql = "select DNo from tbl_drugs";
        
        try
        {
            st = Conn.createStatement();
            rs = st.executeQuery(sql);
            rs.last();
            
            this.txt_DNo.setText(String.valueOf(rs.getInt("Dno")+1));
            txt_date.setEditable(false);
            txt_date.setText(date);
            
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jLabel1 = new javax.swing.JLabel();
        txt_DNo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_Dname = new javax.swing.JTextField();
        txt_cutOff = new javax.swing.JTextField();
        txt_qty = new javax.swing.JTextField();
        txt_ageRange = new javax.swing.JTextField();
        txt_amount = new javax.swing.JTextField();
        txt_date = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_medi = new javax.swing.JTable();
        btn_insert = new javax.swing.JButton();
        btn_cancel = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Drug Number ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 40, 99, 20);

        txt_DNo.setBackground(new java.awt.Color(255, 255, 255));
        txt_DNo.setForeground(new java.awt.Color(0, 0, 0));
        txt_DNo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.lightGray));

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, txt_DNo, org.jdesktop.beansbinding.ELProperty.create("${editable}false"), txt_DNo, org.jdesktop.beansbinding.BeanProperty.create("editable"));
        bindingGroup.addBinding(binding);

        getContentPane().add(txt_DNo);
        txt_DNo.setBounds(220, 30, 151, 30);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Drug");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 90, 80, 20);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Cut-off(mg/ml)");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 140, 120, 20);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Quantity");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 190, 90, 20);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Age Range");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 240, 100, 20);

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Available Amount");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(50, 290, 170, 20);

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Date Inserted");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(50, 340, 130, 20);

        txt_Dname.setBackground(new java.awt.Color(255, 255, 255));
        txt_Dname.setForeground(new java.awt.Color(0, 0, 0));
        txt_Dname.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.lightGray));
        getContentPane().add(txt_Dname);
        txt_Dname.setBounds(220, 80, 151, 30);

        txt_cutOff.setBackground(new java.awt.Color(255, 255, 255));
        txt_cutOff.setForeground(new java.awt.Color(0, 0, 0));
        txt_cutOff.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.lightGray));
        txt_cutOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cutOffActionPerformed(evt);
            }
        });
        getContentPane().add(txt_cutOff);
        txt_cutOff.setBounds(220, 130, 151, 30);

        txt_qty.setBackground(new java.awt.Color(255, 255, 255));
        txt_qty.setForeground(new java.awt.Color(0, 0, 0));
        txt_qty.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.lightGray));
        getContentPane().add(txt_qty);
        txt_qty.setBounds(220, 180, 151, 30);

        txt_ageRange.setBackground(new java.awt.Color(255, 255, 255));
        txt_ageRange.setForeground(new java.awt.Color(0, 0, 0));
        txt_ageRange.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.lightGray));
        getContentPane().add(txt_ageRange);
        txt_ageRange.setBounds(220, 230, 151, 30);

        txt_amount.setBackground(new java.awt.Color(255, 255, 255));
        txt_amount.setForeground(new java.awt.Color(0, 0, 0));
        txt_amount.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.lightGray));
        getContentPane().add(txt_amount);
        txt_amount.setBounds(220, 280, 151, 30);

        txt_date.setEditable(false);
        txt_date.setBackground(new java.awt.Color(255, 255, 255));
        txt_date.setForeground(new java.awt.Color(0, 0, 0));
        txt_date.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.lightGray));
        getContentPane().add(txt_date);
        txt_date.setBounds(220, 330, 151, 30);

        tbl_medi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Drug Number", "Drug", "Cut-off", "Qunatity", "Age Range", "Available Amount", "Date Updated"
            }
        ));
        jScrollPane1.setViewportView(tbl_medi);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(401, 29, 768, 403);

        btn_insert.setBackground(new java.awt.Color(255, 255, 255));
        btn_insert.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btn_insert.setForeground(new java.awt.Color(0, 0, 0));
        btn_insert.setText("Insert");
        btn_insert.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.lightGray));
        btn_insert.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_insertActionPerformed(evt);
            }
        });
        getContentPane().add(btn_insert);
        btn_insert.setBounds(60, 400, 120, 30);

        btn_cancel.setBackground(new java.awt.Color(255, 255, 255));
        btn_cancel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btn_cancel.setForeground(new java.awt.Color(0, 0, 0));
        btn_cancel.setText("Cancel");
        btn_cancel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.lightGray));
        btn_cancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cancel);
        btn_cancel.setBounds(230, 400, 130, 30);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medicalapp/nsbmzz.png"))); // NOI18N
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jLabel8);
        jLabel8.setBounds(-1, -5, 1180, 480);

        bindingGroup.bind();

        setSize(new java.awt.Dimension(1203, 535));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
        String sql = "select DNo from tbl_drugs";
        
        try
        {
            st = Conn.createStatement();
            rs = st.executeQuery(sql);
            rs.last();
            
            this.txt_DNo.setText(String.valueOf(rs.getInt("Dno")+1));
            txt_date.setEditable(false);
            txt_date.setText(date);
            
            
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_formWindowOpened

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        NurseMain nm = new NurseMain();
        nm.setVisible(true);
    }//GEN-LAST:event_btn_cancelActionPerformed

    private void btn_insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_insertActionPerformed
        // TODO add your handling code here:
        
        if(txt_Dname.getText().trim().isEmpty() && txt_cutOff.getText().trim().isEmpty() && txt_qty.getText().trim().isEmpty() && txt_ageRange.getText().trim().isEmpty() && txt_amount.getText().trim().isEmpty()  )
        {
            JOptionPane.showMessageDialog(null,"Please enter the Data");
        }
        else if(txt_Dname.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(null,"Please enter the Drugs Name");
        }
        else if(txt_cutOff.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(null,"Please enter the cut-off value");
        }
        else if(txt_qty.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(null,"Please enter the Quantity");
        }
        else if(txt_ageRange.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(null,"Please enter the age range");
        }
        else if(txt_amount.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(null,"Please enter the Available amount");
        }
        else{
        
        
        String sql = "Insert into tbl_drugs(`DNO`,`DName`,`cutOff`,`Qty`,`ARange`,`Amount`,`Date`) values ('"+txt_DNo.getText()+"','"+txt_Dname.getText()+"','"+txt_cutOff.getText()+"','"+txt_qty.getText()+"','"+txt_ageRange.getText()+"','"+txt_amount.getText()+"','"+date+"')";
        
        try{
            st = Conn.createStatement();
            if((st.executeUpdate(sql))==1)
            {
                JOptionPane.showMessageDialog(null," Data Saved Successfully ");
                DefaultTableModel model = (DefaultTableModel)tbl_medi.getModel();
                model.setRowCount(0);
                clearData();
                generateDNO();
                showMedicines();
            }
            else
            {
                JOptionPane.showMessageDialog(null," Data not Saved");
            }
            
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        }
    }//GEN-LAST:event_btn_insertActionPerformed

    private void txt_cutOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cutOffActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cutOffActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddMedicines.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddMedicines.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddMedicines.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddMedicines.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddMedicines().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_insert;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_medi;
    private javax.swing.JTextField txt_DNo;
    private javax.swing.JTextField txt_Dname;
    private javax.swing.JTextField txt_ageRange;
    private javax.swing.JTextField txt_amount;
    private javax.swing.JTextField txt_cutOff;
    private javax.swing.JTextField txt_date;
    private javax.swing.JTextField txt_qty;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

}
