/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package medicalapp;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

public class AddRecord extends javax.swing.JFrame {

    
    Connection conn;
    ResultSet rs,rs1;
    PreparedStatement pst,pst1;
    Statement st;
    String date = java.time.LocalDate.now().toString();
    String Name;
    
    
    public AddRecord() {
        initComponents();
        conn = connection.ConnectDb();
    }
    
   
    
     /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        txtLastDate = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMedi = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        txtStudentID = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtSymp = new javax.swing.JTextArea();
        txtName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtMedi1 = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Last record Added");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(480, 40, 170, 30);

        txtLastDate.setEditable(false);
        txtLastDate.setBackground(new java.awt.Color(255, 255, 255));
        txtLastDate.setForeground(new java.awt.Color(0, 0, 0));
        txtLastDate.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.lightGray));
        getContentPane().add(txtLastDate);
        txtLastDate.setBounds(660, 40, 160, 30);

        btnAdd.setBackground(new java.awt.Color(255, 255, 255));
        btnAdd.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(0, 0, 0));
        btnAdd.setText(" Add Record");
        btnAdd.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.lightGray));
        btnAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd);
        btnAdd.setBounds(860, 550, 140, 40);

        btnSearch.setBackground(new java.awt.Color(255, 255, 255));
        btnSearch.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(0, 0, 0));
        btnSearch.setText("Search");
        btnSearch.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.lightGray));
        btnSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearch);
        btnSearch.setBounds(870, 40, 220, 70);

        btnCancel.setBackground(new java.awt.Color(255, 255, 255));
        btnCancel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(0, 0, 0));
        btnCancel.setText("Back");
        btnCancel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.lightGray));
        btnCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancel);
        btnCancel.setBounds(1050, 550, 120, 40);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Symptoms");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(170, 190, 290, 60);

        txtMedi.setBackground(new java.awt.Color(255, 255, 255));
        txtMedi.setColumns(20);
        txtMedi.setForeground(new java.awt.Color(0, 0, 0));
        txtMedi.setRows(5);
        txtMedi.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.lightGray));
        jScrollPane1.setViewportView(txtMedi);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(320, 410, 630, 100);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Student ID");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(110, 40, 130, 30);

        txtStudentID.setBackground(new java.awt.Color(255, 255, 255));
        txtStudentID.setForeground(new java.awt.Color(0, 0, 0));
        txtStudentID.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.lightGray));
        getContentPane().add(txtStudentID);
        txtStudentID.setBounds(260, 40, 170, 30);

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Medicines");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(170, 310, 270, 60);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Student Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(110, 90, 150, 30);

        txtSymp.setBackground(new java.awt.Color(255, 255, 255));
        txtSymp.setColumns(20);
        txtSymp.setForeground(new java.awt.Color(0, 0, 0));
        txtSymp.setRows(5);
        txtSymp.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.lightGray));
        jScrollPane2.setViewportView(txtSymp);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(320, 170, 630, 100);

        txtName.setEditable(false);
        txtName.setBackground(new java.awt.Color(255, 255, 255));
        txtName.setForeground(new java.awt.Color(0, 0, 0));
        txtName.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.lightGray));
        getContentPane().add(txtName);
        txtName.setBounds(260, 90, 170, 30);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Student age");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(480, 90, 150, 30);

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Special notes");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(170, 430, 290, 60);

        txtAge.setEditable(false);
        txtAge.setBackground(new java.awt.Color(255, 255, 255));
        txtAge.setForeground(new java.awt.Color(0, 0, 0));
        txtAge.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.lightGray));
        getContentPane().add(txtAge);
        txtAge.setBounds(660, 90, 160, 30);

        txtMedi1.setBackground(new java.awt.Color(255, 255, 255));
        txtMedi1.setColumns(20);
        txtMedi1.setForeground(new java.awt.Color(0, 0, 0));
        txtMedi1.setRows(5);
        txtMedi1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.lightGray));
        jScrollPane3.setViewportView(txtMedi1);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(320, 290, 630, 100);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medicalapp/nsbmzz.png"))); // NOI18N
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jLabel8);
        jLabel8.setBounds(2, -5, 1250, 620);

        setSize(new java.awt.Dimension(1280, 678));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void clearData()
    {
        txtStudentID.setText("");txtAge.setText("");txtLastDate.setText("");txtMedi1.setText("");
        txtName.setText("");txtSymp.setText("");txtMedi.setText("");
    }
    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:

        String sql = "select * from student where student_id = ?";
        String sql1 = "select * from report where student_id = ?";
        
        try{
            pst = conn.prepareStatement(sql);
            pst.setString(1, txtStudentID.getText());
            rs = pst.executeQuery();
            
            pst1 = conn.prepareStatement(sql1);
            pst1.setString(1, txtStudentID.getText());
            rs1 = pst1.executeQuery();            
            
            if(rs.next()&& rs1.last()){
                String a1 = rs.getString("name");
                txtName.setText(a1);
                String a2 = rs.getString("age");
                txtAge.setText(a2);
                String a3 = rs1.getString("date");
                txtLastDate.setText(a3);
                rs.close(); rs1.close();
                pst.close(); pst1.close();              
                   
        
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Student Id is incorrect");
            }

        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }finally{
            try{
                rs.close();rs1.close();
                pst.close(); pst1.close();
            }catch(Exception e)
            {

            }
        }

    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        
        if(txtStudentID.getText().trim().isEmpty() && txtSymp.getText().trim().isEmpty() && txtMedi1.getText().trim().isEmpty() && txtMedi.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Please search the student id and enter data");
        }
        else if(txtStudentID.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Please search the student first");
        }
        else if(txtSymp.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Please enter the Symptopms");
        }
        else if(txtMedi1.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Please enter the medicines given");
        }
        else if(txtMedi.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Please enter special notes");
        }
        else{
        
        //String date = java.time.LocalDate.now().toString();
        String sql = "INSERT INTO report(`Student_id`,`symptoms`,`medicines`,`special_notes`,`ref_doc`,`date`) VALUES ('"+txtStudentID.getText()+"','"+txtSymp.getText()+"','"+txtMedi1.getText()+"','"+txtMedi.getText()+"','"+Name+"','"+date+"')";
        
        try{
            st = conn.createStatement();
            if((st.executeUpdate(sql))==1)
            {
                JOptionPane.showMessageDialog(null," Data Saved Successfully ");
                clearData();
            }
            else
            {
                JOptionPane.showMessageDialog(null," Data not Saved");
            }
            
            
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        DoctorMain d = new DoctorMain();
        d.setVisible(true);
        
    }//GEN-LAST:event_btnCancelActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        String sql = "select `Display_name` from `tbl_login_history`";
        
        try
        {
            st = conn.createStatement();
            rs = st.executeQuery(sql);
            rs.last();            
            
            Name = rs.getString("Display_name");           
            
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddRecord().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtLastDate;
    private javax.swing.JTextArea txtMedi;
    private javax.swing.JTextArea txtMedi1;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtStudentID;
    private javax.swing.JTextArea txtSymp;
    // End of variables declaration//GEN-END:variables
}
