/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package medicalapp;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Chamuditha Jayaweera
 */

public class DoctorMain extends javax.swing.JFrame {

    /**
     * Creates new form DoctorMain
     */
        
    Connection Conn;
    ResultSet rs;
    Statement st;
    
    public DoctorMain() {
        initComponents();       
        Conn = connection.ConnectDb();
    }
            
       
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnViewHistory = new javax.swing.JButton();
        btnAddHistory = new javax.swing.JButton();
        tbnAvailability = new javax.swing.JButton();
        lbl_name = new javax.swing.JLabel();
        btn_logOut = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        btnViewHistory.setBackground(new java.awt.Color(255, 255, 255));
        btnViewHistory.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnViewHistory.setForeground(new java.awt.Color(0, 0, 0));
        btnViewHistory.setText("View Patient Record History");
        btnViewHistory.setBorder(null);
        btnViewHistory.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnViewHistory.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnViewHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewHistoryActionPerformed(evt);
            }
        });
        getContentPane().add(btnViewHistory);
        btnViewHistory.setBounds(420, 180, 260, 100);

        btnAddHistory.setBackground(new java.awt.Color(255, 255, 255));
        btnAddHistory.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnAddHistory.setForeground(new java.awt.Color(0, 0, 0));
        btnAddHistory.setText("Add Patient record");
        btnAddHistory.setBorder(null);
        btnAddHistory.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddHistoryActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddHistory);
        btnAddHistory.setBounds(790, 180, 190, 100);

        tbnAvailability.setBackground(new java.awt.Color(255, 255, 255));
        tbnAvailability.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        tbnAvailability.setForeground(new java.awt.Color(0, 0, 0));
        tbnAvailability.setText("Check Availablity");
        tbnAvailability.setBorder(null);
        tbnAvailability.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tbnAvailability.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbnAvailabilityActionPerformed(evt);
            }
        });
        getContentPane().add(tbnAvailability);
        tbnAvailability.setBounds(100, 180, 200, 100);

        lbl_name.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lbl_name);
        lbl_name.setBounds(598, 23, 207, 52);

        btn_logOut.setBackground(new java.awt.Color(255, 255, 255));
        btn_logOut.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btn_logOut.setForeground(new java.awt.Color(0, 0, 0));
        btn_logOut.setText("Logout");
        btn_logOut.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.lightGray, java.awt.Color.white));
        btn_logOut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_logOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logOutActionPerformed(evt);
            }
        });
        getContentPane().add(btn_logOut);
        btn_logOut.setBounds(960, 460, 100, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medicalapp/nsbmzz.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(1, 2, 1090, 510);

        setSize(new java.awt.Dimension(1109, 566));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tbnAvailabilityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbnAvailabilityActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);               
        new SearchMedicine().setVisible(true);
        
    }//GEN-LAST:event_tbnAvailabilityActionPerformed

    private void btnViewHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewHistoryActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        viewHistory v = new viewHistory();
        v.setVisible(true);
    }//GEN-LAST:event_btnViewHistoryActionPerformed

    private void btnAddHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddHistoryActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new AddRecord().setVisible(true);
    }//GEN-LAST:event_btnAddHistoryActionPerformed

    private void btn_logOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logOutActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        loginForm lf = new loginForm();
        lf.setVisible(true);
        JOptionPane.showMessageDialog(null,"Successfully Logout" );
    }//GEN-LAST:event_btn_logOutActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
        String sql = "select `Display_name` from `tbl_login_history`";
        
        try
        {
            st = Conn.createStatement();
            rs = st.executeQuery(sql);
            rs.last();            
            
            this.lbl_name.setText(rs.getString("Display_name"));           
            
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DoctorMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DoctorMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DoctorMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoctorMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DoctorMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddHistory;
    private javax.swing.JButton btnViewHistory;
    private javax.swing.JButton btn_logOut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JButton tbnAvailability;
    // End of variables declaration//GEN-END:variables
}
