/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package medicalapp;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Chamuditha Jayaweera
 */
public class SearchMedicine extends javax.swing.JFrame {

    /**
     * Creates new form SearchMedicine
     */
    
    Connection conn;
    ResultSet rs;
    PreparedStatement pst;
    Statement st;
    
    public SearchMedicine() {
        initComponents();
        conn = connection.ConnectDb(); 
    }
    
    
    
     public ArrayList<Medicines> medicineList()
    {
        ArrayList<Medicines> medicineList = new ArrayList<>();
        
        String sql = "select * from tbl_drugs where DName = ? ";
        
        try{
            pst = conn.prepareStatement(sql);
           pst.setString(1, txt_Dname.getText());
           rs = pst.executeQuery();
            Medicines medicines;
            while(rs.next())
            {
                medicines = new Medicines(rs.getInt("Dno"),rs.getString("Dname"),rs.getString("cutOff"),rs.getInt("Qty"),rs.getString("ARange"),rs.getInt("Amount"),rs.getString("Date"));
                medicineList.add(medicines);
            }
            
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        
        return medicineList;
    }
     public void showMedicines()
    {
        ArrayList<Medicines> list = medicineList();
        DefaultTableModel model = (DefaultTableModel)tbl_medi.getModel();
        Object[] row = new Object[7];
        for(int i= 0;i<list.size();i++)
        {
            row[0] = list.get(i).getDno();
            row[1] = list.get(i).getDname();
            row[2] = list.get(i).getCutOff();
            row[3] = list.get(i).getQty();
            row[4] = list.get(i).getARange();
            row[5] = list.get(i).getAmount();
            row[6] = list.get(i).getDate();
            model.addRow(row);
        }
        
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_medi = new javax.swing.JTable();
        txt_Dname = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btn_search = new javax.swing.JButton();
        btn_return = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        getContentPane().setLayout(null);

        tbl_medi.setBackground(new java.awt.Color(255, 255, 255));
        tbl_medi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Drug Number", "Drug", "Cut-off", "Qunatity", "Age Range", "Available Amount", "Date Updated"
            }
        ));
        jScrollPane1.setViewportView(tbl_medi);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(170, 150, 962, 403);

        txt_Dname.setBackground(new java.awt.Color(255, 255, 255));
        txt_Dname.setForeground(new java.awt.Color(0, 0, 0));
        txt_Dname.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, new java.awt.Color(255, 255, 255), java.awt.Color.lightGray, java.awt.Color.lightGray));
        getContentPane().add(txt_Dname);
        txt_Dname.setBounds(250, 60, 370, 40);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Drug Name");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(110, 60, 140, 40);

        btn_search.setBackground(new java.awt.Color(255, 255, 255));
        btn_search.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btn_search.setForeground(new java.awt.Color(0, 0, 0));
        btn_search.setText("Search");
        btn_search.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, new java.awt.Color(255, 255, 255), java.awt.Color.lightGray, java.awt.Color.lightGray));
        btn_search.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchActionPerformed(evt);
            }
        });
        getContentPane().add(btn_search);
        btn_search.setBounds(700, 60, 210, 40);

        btn_return.setBackground(new java.awt.Color(255, 255, 255));
        btn_return.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btn_return.setForeground(new java.awt.Color(0, 0, 0));
        btn_return.setText("Back");
        btn_return.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, new java.awt.Color(255, 255, 255), java.awt.Color.lightGray, java.awt.Color.lightGray));
        btn_return.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_return.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_returnActionPerformed(evt);
            }
        });
        getContentPane().add(btn_return);
        btn_return.setBounds(930, 60, 200, 40);

        jLabel2.setBackground(new java.awt.Color(0, 255, 51));
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medicalapp/image/nsbmzz.png"))); // NOI18N
        jLabel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, new java.awt.Color(255, 255, 255), java.awt.Color.lightGray, java.awt.Color.lightGray));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-1, 0, 1250, 620);

        setSize(new java.awt.Dimension(1277, 684));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed
        // TODO add your handling code here:
        if(txt_Dname.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Please enter the Drugs Name!");
        }
        else{
            DefaultTableModel model = (DefaultTableModel)tbl_medi.getModel();
            model.setRowCount(0);
            showMedicines();
        }
        
    }//GEN-LAST:event_btn_searchActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)tbl_medi.getModel();
        model.setRowCount(0);
    }//GEN-LAST:event_formMouseClicked

    private void btn_returnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_returnActionPerformed
        // TODO add your handling code here:
        
        String sql = "select `role` from `tbl_login_history`";
        
        try
        {
            st = conn.createStatement();
            rs = st.executeQuery(sql);
            rs.last();            
            
            String role = rs.getString("role");    
            
            if(role.equals("1"))
            {
                this.setVisible(false);
                new DoctorMain().setVisible(true);
            }
            else
            {
                this.setVisible(false);
                new NurseMain().setVisible(true);
            }
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Hello");
        }
        
                
                
    }//GEN-LAST:event_btn_returnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchMedicine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_return;
    private javax.swing.JButton btn_search;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_medi;
    private javax.swing.JTextField txt_Dname;
    // End of variables declaration//GEN-END:variables
}
