/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package medicalapp;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Chamuditha Jayaweera
 */
public class UpdateMedicines extends javax.swing.JFrame {

    /**
     * Creates new form UpdateMedicines
     */
    Connection Conn;
    ResultSet rs;
    PreparedStatement pst;
    Statement st;
    String date = java.time.LocalDate.now().toString();

    
    public UpdateMedicines() {
        initComponents();
        Conn = connection.ConnectDb();        
    }
    
    public ArrayList<Medicines> medicineList()
    {
        ArrayList<Medicines> medicineList = new ArrayList<>();
        
        String sql = "select * from tbl_drugs where DName = ? ";
        
        try{
            pst = Conn.prepareStatement(sql);
           pst.setString(1, txt_Dname.getText());
           rs = pst.executeQuery();
            Medicines medicines;
            while(rs.next())
            {
                medicines = new Medicines(rs.getInt("Dno"),rs.getString("Dname"),rs.getString("cutOff"),rs.getInt("Qty"),rs.getString("ARange"),rs.getInt("Amount"),rs.getString("Date"));
                medicineList.add(medicines);
            }
            
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        
        return medicineList;
    }
    
    public void showMedicines()
    {
        ArrayList<Medicines> list = medicineList();
        DefaultTableModel model = (DefaultTableModel)tbl_medi.getModel();
        Object[] row = new Object[7];
        for(int i= 0;i<list.size();i++)
        {
            row[0] = list.get(i).getDno();
            row[1] = list.get(i).getDname();
            row[2] = list.get(i).getCutOff();
            row[3] = list.get(i).getQty();
            row[4] = list.get(i).getARange();
            row[5] = list.get(i).getAmount();
            row[6] = list.get(i).getDate();
            model.addRow(row);
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_cutOff = new javax.swing.JTextField();
        txt_qty = new javax.swing.JTextField();
        txt_ageRange = new javax.swing.JTextField();
        txt_amount = new javax.swing.JTextField();
        txt_date = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_medi = new javax.swing.JTable();
        btn_update = new javax.swing.JButton();
        btn_cancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txt_DNo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_Dname = new javax.swing.JTextField();
        btn_search = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        txt_cutOff.setBackground(new java.awt.Color(255, 255, 255));
        txt_cutOff.setForeground(new java.awt.Color(0, 0, 0));
        txt_cutOff.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.white, java.awt.Color.lightGray, java.awt.Color.lightGray));
        getContentPane().add(txt_cutOff);
        txt_cutOff.setBounds(220, 140, 190, 30);

        txt_qty.setBackground(new java.awt.Color(255, 255, 255));
        txt_qty.setForeground(new java.awt.Color(0, 0, 0));
        txt_qty.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.white, java.awt.Color.lightGray, java.awt.Color.lightGray));
        getContentPane().add(txt_qty);
        txt_qty.setBounds(220, 200, 190, 30);

        txt_ageRange.setBackground(new java.awt.Color(255, 255, 255));
        txt_ageRange.setForeground(new java.awt.Color(0, 0, 0));
        txt_ageRange.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.white, java.awt.Color.lightGray, java.awt.Color.lightGray));
        getContentPane().add(txt_ageRange);
        txt_ageRange.setBounds(220, 260, 190, 30);

        txt_amount.setBackground(new java.awt.Color(255, 255, 255));
        txt_amount.setForeground(new java.awt.Color(0, 0, 0));
        txt_amount.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.white, java.awt.Color.lightGray, java.awt.Color.lightGray));
        getContentPane().add(txt_amount);
        txt_amount.setBounds(220, 320, 190, 30);

        txt_date.setEditable(false);
        txt_date.setBackground(new java.awt.Color(255, 255, 255));
        txt_date.setForeground(new java.awt.Color(0, 0, 0));
        txt_date.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.white, java.awt.Color.lightGray, java.awt.Color.lightGray));
        getContentPane().add(txt_date);
        txt_date.setBounds(220, 380, 190, 30);

        tbl_medi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Drug Number", "Drug", "Cut-off", "Qunatity", "Age Range", "Available Amount", "Date Updated"
            }
        ));
        tbl_medi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_mediMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_medi);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(440, 50, 790, 520);

        btn_update.setBackground(new java.awt.Color(255, 255, 255));
        btn_update.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btn_update.setForeground(new java.awt.Color(0, 0, 0));
        btn_update.setText("Update");
        btn_update.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.white, java.awt.Color.lightGray, java.awt.Color.lightGray));
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });
        getContentPane().add(btn_update);
        btn_update.setBounds(20, 530, 110, 40);

        btn_cancel.setBackground(new java.awt.Color(255, 255, 255));
        btn_cancel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btn_cancel.setForeground(new java.awt.Color(0, 0, 0));
        btn_cancel.setText("Cancel");
        btn_cancel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.white, java.awt.Color.lightGray, java.awt.Color.lightGray));
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cancel);
        btn_cancel.setBounds(280, 530, 120, 40);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Drug Number ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(60, 80, 130, 40);

        txt_DNo.setEditable(false);
        txt_DNo.setBackground(new java.awt.Color(255, 255, 255));
        txt_DNo.setForeground(new java.awt.Color(0, 0, 0));
        txt_DNo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.white, java.awt.Color.lightGray, java.awt.Color.lightGray));
        getContentPane().add(txt_DNo);
        txt_DNo.setBounds(220, 80, 190, 30);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Drug Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 20, 130, 40);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Cut-off(mg/ml)");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 140, 130, 40);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Quantity");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 190, 80, 40);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Age Range");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(60, 250, 110, 40);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Available Amount");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(60, 310, 160, 40);

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Date updated");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(60, 370, 120, 40);

        txt_Dname.setBackground(new java.awt.Color(255, 255, 255));
        txt_Dname.setForeground(new java.awt.Color(0, 0, 0));
        txt_Dname.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.white, java.awt.Color.lightGray, java.awt.Color.lightGray));
        getContentPane().add(txt_Dname);
        txt_Dname.setBounds(220, 20, 190, 30);

        btn_search.setBackground(new java.awt.Color(255, 255, 255));
        btn_search.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btn_search.setForeground(new java.awt.Color(0, 0, 0));
        btn_search.setText("Search");
        btn_search.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.white, java.awt.Color.lightGray, java.awt.Color.lightGray));
        btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchActionPerformed(evt);
            }
        });
        getContentPane().add(btn_search);
        btn_search.setBounds(140, 460, 140, 40);

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medicalapp/image/nsbmzz.png"))); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(2, -3, 1250, 620);

        setSize(new java.awt.Dimension(1270, 675));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        // TODO add your handling code here:
        
        if(txt_DNo.getText().trim().isEmpty() && txt_Dname.getText().trim().isEmpty() && txt_ageRange.getText().trim().isEmpty() && txt_amount.getText().trim().isEmpty() && txt_cutOff.getText().trim().isEmpty() && txt_date.getText().trim().isEmpty() && txt_qty.getText().trim().isEmpty()   )
        {
            JOptionPane.showMessageDialog(null,"Plaese Enter the data");
        }
        else if(txt_DNo.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(null,"Plaese Select Drugs from table");
        }
        else if(txt_Dname.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(null,"Plaese Enter the name");
        }
        else if(txt_ageRange.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(null,"Plaese Enter the Age range");
        }
        else if(txt_amount.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(null,"Plaese Enter the Available Amount");
        }
        else if(txt_cutOff.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(null,"Plaese Enter the cut-off value");
        }
        else{
            
        
        
        String sql = "update tbl_drugs set cutOff= '"+txt_cutOff.getText()+"', Qty='"+txt_qty.getText()+"', ARange='"+txt_ageRange.getText()+"', Amount ='"+txt_amount.getText()+"', Date='"+date+"' where DNo='"+txt_DNo.getText()+"'";
        
        try{
            st = Conn.createStatement();
            if((st.executeUpdate(sql)) ==1 )
            {
                JOptionPane.showMessageDialog(null,"Data Updated Succefully");
                DefaultTableModel model = (DefaultTableModel)tbl_medi.getModel();
                model.setRowCount(0);
                showMedicines();
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Data not updated Succefully");
            }
            
            
            
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        }
    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)tbl_medi.getModel();
        model.setRowCount(0);
        showMedicines();
    }//GEN-LAST:event_btn_searchActionPerformed

    private void tbl_mediMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_mediMouseClicked
        // TODO add your handling code here:
        int i = tbl_medi.getSelectedRow();
        TableModel model = tbl_medi.getModel();
        
        txt_DNo.setText(model.getValueAt(i, 0).toString());
        txt_Dname.setText(model.getValueAt(i, 1).toString());
        txt_cutOff.setText(model.getValueAt(i, 2).toString());
        txt_qty.setText(model.getValueAt(i, 3).toString());
        txt_ageRange.setText(model.getValueAt(i, 4).toString());
        txt_amount.setText(model.getValueAt(i, 5).toString());
        txt_date.setText(model.getValueAt(i, 6).toString());
    }//GEN-LAST:event_tbl_mediMouseClicked

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new NurseMain().setVisible(true);
    }//GEN-LAST:event_btn_cancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateMedicines.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateMedicines.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateMedicines.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateMedicines.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateMedicines().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_search;
    private javax.swing.JButton btn_update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_medi;
    private javax.swing.JTextField txt_DNo;
    private javax.swing.JTextField txt_Dname;
    private javax.swing.JTextField txt_ageRange;
    private javax.swing.JTextField txt_amount;
    private javax.swing.JTextField txt_cutOff;
    private javax.swing.JTextField txt_date;
    private javax.swing.JTextField txt_qty;
    // End of variables declaration//GEN-END:variables
}
